name = "xugou-backend"
main = "src/index.ts"
compatibility_date = "2025-03-10"
compatibility_flags = ["nodejs_compat"]

# 添加定时触发器，每分钟执行一次监控检查
[triggers]
crons = ["* * * * *"]

[[d1_databases]]
binding = "DB"
database_name = "my-api"
database_id = "17425ece-265c-4a21-a1c7-80ff8332ca90"

[version_metadata]
binding = "CF_VERSION_METADATA"
